name: Publish package to GitHub Packages
on:
  push:
  #release:
  #  types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup dependencies
        run: make smithy-go-publish-local
      
      - name: Patch local smithy-go
        run: patch -u /tmp/smithy-go-local/codegen/build.gradle.kts -i smithy-go-publish-github.patch

      - name: Publish smithy-go-codegen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: (cd /tmp/smithy-go-local/codegen/smithy-go-codegen && ../gradlew publish)

      - name: Publish smithy-aws-go-codegen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: (cd codegen/smithy-aws-go-codegen && ../gradlew publish)
